"""Architecture E2E: WebUI → project.json → orchestration → prompts → plans → manuscript → citations → layout → QA → outputs.

The job is generated by the real WebUI code (tests/webui_cli.ts `zipfiles`, i.e. src/job.ts + src/architecture.ts) in
AUTO mode with:
  - free-text intent 「章末問題はいらない。ケースを多く、図表を多く。固すぎない文章で。」
  - footnote citations with a numbered, grouped bibliography
  - an evidence set (the mini-book sources), a background experience article, an uploaded figure for 第2章 and a
    layout-reference PDF
Then `bookorder goal` runs to STATUS: COMPLETE with the scripted mock agent of tests/mini_e2e.py, extended for the
publication-planning and visual-planning phases. The assertions follow the settings through every stage.

Requirements: Node 22+, Python 3.10+, Pandoc and Typst. Usage: python tests/architecture_e2e.py [--keep]
"""
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import zipfile

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tests"))
import mini_e2e  # noqa: E402
from mini_e2e import AGENT, FIXTURE, MockAgent, SUMMARIES, cli, run_goal, serve  # noqa: E402

WORK = REPO / ".test-output/architecture-e2e/publishing-job"
EXTRA = REPO / "tests/fixtures/architecture-e2e"
INSTRUCTIONS = "章末問題はいらない。ケースを多く、図表を多く。固すぎない文章で。\nアップロードした図は第2章の処理の流れを説明する場所で使うこと。"
CONTENT_INTENT = {
    "ch-foundations": ("注意機構が生まれた理由を、翻訳モデルの限界から直感的に理解させる", ["key_point", "warning_box"], ["process_diagram"]),
    "ch-mechanism": ("自己注意の計算と構造を、式・図・比較表で組み立てて理解させる", ["figure", "table", "summary"], ["process_diagram", "annotated_image", "comparison_table"]),
    "ch-training": ("学習とスケーリングの実務判断を、ケースと次の行動で身につけさせる", ["warning_box", "case_study", "next_actions"], []),
    "ch-evaluation": ("評価の読み方を身につけ、本書全体を自分の判断に結びつけさせる", ["key_point"], []),
}


def generate(base):
    """The job ZIP exactly as the WebUI generates it (Advanced publishing with per-file roles)."""
    if WORK.parent.exists(): shutil.rmtree(WORK.parent)
    WORK.parent.mkdir(parents=True)
    urls = [f"{base}/transformer-architecture.html", f"{base}/training-dynamics.html", f"{base}/scaling-debate.html", f"{base}/history.md",
            f"{base}/field-notes.html", f"{base}/layout-sample-page.html"]
    spec = {"form": {"title": "注意機構から大規模言語モデルへ", "description": "注意機構の原理から学習・評価までを一貫して解説する小冊子",
                     "targetReaders": "機械学習の基礎を知るエンジニア", "targetPages": 8, "instructions": INSTRUCTIONS, "urls": "\n".join(urls),
                     "uiMode": "advanced", "citationStyle": "note",
                     "bibliography": {"footnoteStyle": "full", "numbering": "numbered", "scope": "per_group"},
                     "architecture": {"mode": "auto"},
                     "outputs": {"canonical_markdown": True, "docx": True, "semantic_html": True, "pdf": True, "static_site": True, "epub": False}},
            "urlUsage": {f"{base}/field-notes.html": {"role": "background", "authority": "professional_experience", "intendedChapter": "第4章",
                                                      "notes": "現場の実感の参考。事実の根拠にはしない"},
                         f"{base}/layout-sample-page.html": {"role": "layout_reference", "notes": "見出しと余白の参考"},
                         f"{base}/transformer-architecture.html": {"role": "evidence", "authority": "expert_commentary", "intendedUsage": "第2章の構造の説明"}},
            "files": [{"path": str(FIXTURE / "sources/attention-basics.md"), "usage": {"role": "evidence", "authority": "textbook"}},
                      {"path": str(FIXTURE / "sources/evaluation.txt"), "usage": {"role": "evidence"}},
                      {"path": str(REPO / "tests/fixtures/reference-1.pdf"), "usage": {"role": "evidence"}},
                      {"path": str(EXTRA / "practitioner-notes.md"), "usage": {"role": "further_reading", "authority": "professional_experience"}},
                      {"path": str(REPO / "tests/fixtures/pipeline.png"), "type": "image/png",
                       "usage": {"role": "asset", "assetRole": "inline_figure", "intendedChapter": "第2章", "caption": "Transformerの処理パイプライン",
                                 "notes": "第2章の処理の流れを説明する場所で使用。表紙には使用しない。", "priority": "high"}},
                      {"path": str(REPO / "tests/fixtures/reference-2.pdf"), "name": "layout-sample.pdf",
                       "usage": {"role": "layout_reference", "assetRole": "layout_reference", "notes": "余白と段組、見出しの階層だけ参考にする"}}]}
    out = WORK.parent / "job.zip"
    result = subprocess.run(["node", "--experimental-strip-types", "tests/webui_cli.ts", "zipfiles", json.dumps(spec, ensure_ascii=False), str(out)],
                            cwd=REPO, capture_output=True, text=True, encoding="utf-8")
    if result.returncode: raise AssertionError("WebUI job generation failed: " + result.stdout + result.stderr)
    with zipfile.ZipFile(out) as z: z.extractall(WORK.parent)
    project = json.loads((WORK / "project.json").read_text(encoding="utf-8"))
    project["book"]["author"] = "BookOrder Architecture-E2E"
    (WORK / "project.json").write_text(json.dumps(project, ensure_ascii=False, indent=2), encoding="utf-8")
    (WORK / "book.design.yaml").write_text(json.dumps({**json.loads((WORK / "book.design.yaml").read_text(encoding="utf-8")),
                                                        "art_direction": "落ち着いた技術書。アクセントは青緑。"}, ensure_ascii=False), encoding="utf-8")
    return urls


def job_yaml(path):
    import common
    return common.yaml_data(path)


def unwrap(text, ident):
    return re.sub(r"::: \{\.summary #" + ident + r"\}\n(.*?)\n:::", r"\1", text, flags=re.S)


class ArchitectureAgent(MockAgent):
    def check_intent(self, task):
        phases = ("supplementary_research", "corpus_analysis", "publication_planning", "architecture", "editorial_planning", "visual_planning", "drafting",
                  "chapter_review", "integration", "asset_planning", "asset_generation", "audit", "rewrite", "prose_audit", "prose_editing", "final_audit",
                  "design", "layout", "validation", "build")
        block = task.get("user_intent")
        if task["phase"] in phases:
            assert block and block["verbatim"] == INSTRUCTIONS, f"{task['id']} lacks the verbatim user intent"
            self.intent_tasks.add(task["phase"])
        else:
            assert block is None, f"{task['id']} ({task['phase']}) should not carry user intent"

    def put_json(self, relative, data):
        self.put(relative, json.dumps(data, ensure_ascii=False, indent=1))

    def handle(self, task):
        identifier = task["id"]; kind, _, target = identifier.partition(":")
        mapping, sources = self.ids()
        if identifier == "publication-plan":
            self.log.append(identifier); self.check_intent(task)
            text = "\n".join(task["instructions"])
            assert "AUTO" in text and "layout-references.yaml" in text and "asset-001" in text, "the task names mode, layout reference and uploads"
            intent = job_yaml(WORK / "plan/publication-intent.yaml")
            assert {s["id"] for s in intent["explicit_signals"]} >= {"no_exercises", "more_cases", "more_visuals", "not_stiff"}, intent["explicit_signals"]
            intent["reviewed_by_agent"] = True
            intent["fields"]["use_context"] = {"value": "エンジニアが通勤中と実務の合間に通読し、評価設計の前に読み返す", "origin": "inferred"}
            self.put_json("plan/publication-intent.yaml", intent)
            arch = job_yaml(WORK / "plan/publication-architecture.yaml")
            arch["archetype"]["secondary"] = "practical_guide"
            arch["chapter_strategy"]["strategy"] = "導入は直感、第2章は図と表で構造、第3章はケースと行動、第4章は判断の軸"
            self.put_json("plan/publication-architecture.yaml", arch)
            self.put_json("plan/layout-references.yaml", {"references": [{"asset": "asset-002", "content_used": False,
                "features": {"page_geometry": "B5縦", "margins": "外側広め", "columns": "1段", "heading_hierarchy": "章・節の2階層", "line_length": "40字前後",
                             "body_density": "標準", "figure_text_ratio": "図は各見開きに一つ程度", "caption_style": "図の下に小さく", "whitespace": "章扉に余白"},
                "apply": ["外側余白を広くとる", "見出しは2階層に抑える"], "do_not_copy": ["本文", "図版"]},
                {"asset": "asset-003", "content_used": False, "features": {k: "URLの見本ページで観察" for k in ("page_geometry", "margins", "columns", "heading_hierarchy",
                 "line_length", "body_density", "figure_text_ratio", "caption_style")}, "apply": ["見出しの階層"], "do_not_copy": ["本文"]}]})
            return
        if identifier == "architecture":
            self.log.append(identifier); self.check_intent(task)
            assert any("content_intent" in line for line in task["instructions"]), "the architect is asked for chapter architecture"
            self.copy("plan/book-bible.yaml", "plan/book-bible.yaml")
            self.copy("plan/outline.yaml", "source/metadata/outline.yaml")
            outline = job_yaml(WORK / "source/metadata/outline.yaml")
            for chapter in outline["chapters"]:
                intent, blocks, visuals = CONTENT_INTENT[chapter["id"]]
                chapter.update(content_intent=intent, blocks=blocks, visuals=visuals)
                if chapter["id"] == "ch-evaluation": chapter["sources"]["supporting"] += [mapping["practitioner-notes"], mapping["field-notes"]]
            self.put_json("source/metadata/outline.yaml", outline)
            self.put_json("plan/user-intent.yaml", {"directives": [
                {"id": "intent-001", "source_quote": "章末問題はいらない", "interpretation": "No exercises or quizzes anywhere.", "applies_to": ["publication_planning", "editorial_planning"]},
                {"id": "intent-002", "source_quote": "ケースを多く", "interpretation": "Cases where the chapter is practical.", "applies_to": ["architecture", "drafting"]},
                {"id": "intent-003", "source_quote": "固すぎない文章で", "interpretation": "Approachable voice.", "applies_to": ["drafting", "prose_editing"]}], "conflicts": []})
            return
        if kind == "editorial" and target != "book":
            self.log.append(identifier); self.check_intent(task)
            assert any("Publication architecture (AUTO" in line for line in task["instructions"]), "editorial task states the architecture"
            self.copy(f"editorial/{target}.yaml", f"plan/editorial/{target}.yaml")
            plan = job_yaml(WORK / f"plan/editorial/{target}.yaml")
            if target == "ch-mechanism":
                assert any("asset-001" in line for line in task["instructions"]), "the chapter's uploaded figure is in the task"
                plan["chapter_end"] = [{"type": "key_points", "why": "式・図・表の要点をまとめて第3章の前提にする"}]
                section = next(s for s in plan["sections"] if s["id"] == "sec-mechanism-multihead")
                section.setdefault("devices", []).append({"id": "fig-pipeline", "type": "figure", "why": "ユーザー提供の処理パイプライン図で流れを一望させる",
                    "placement": {"intent": "マルチヘッド注意の説明の後", "position": "section_end"}, "asset_ref": "asset-001", "basis": "source",
                    "source_ids": [mapping["transformer-architecture"]], "information_shape": {"kind": "source_image"}, "visual_type": "annotated_image"})
            elif target == "ch-training":
                plan["chapter_end"] = [{"type": "next_actions", "why": "スケーリングの判断を読者の次の実験計画に移す"}]
                plan["sections"][0].setdefault("devices", []).append({"id": "cs-training-warmup", "type": "case_study", "basis": "hypothetical",
                    "why": "ユーザーの「ケースを多く」に応え、ウォームアップの判断を具体化する", "placement": {"intent": "学習手順の説明の後", "position": "section_end"}})
            else:
                plan["chapter_end"] = []
            self.put_json(f"plan/editorial/{target}.yaml", plan)
            return
        if identifier == "fix-architecture-qa":
            self.log.append(identifier); self.check_intent(task)
            assert any("user_visual_wish_unmet" in line for line in task["instructions"]), task["instructions"]
            arch = job_yaml(WORK / "plan/publication-architecture.yaml")
            arch["qa_waivers"] = [{"rule": "user_visual_wish_unmet", "reason": "8ページの小冊子で、第1・3・4章の内容に図にすべき構造がない（最終レポートに記載）"}]
            self.put_json("plan/publication-architecture.yaml", arch)
            return
        if identifier == "visual-plan":
            self.log.append(identifier); self.check_intent(task)
            data = job_yaml(WORK / "plan/visual-plan.yaml")
            kinds = {"fig-attention-flow": ("process_diagram", "diagram_ir"), "tbl-attention-variants": ("comparison_table", "native_table"),
                     "fig-pipeline": ("annotated_image", "uploaded_asset")}
            for v in data["visuals"]:
                v["type"], v["generation_method"] = kinds[v["id"]]
                v.update(purpose="構造を一目で把握させる", content="要素と関係（本文の該当節から）", reason="文章では順序と関係を同時に保持しにくい",
                         importance="essential", caption_intent="読み取るべき関係を指示する", duplication_check="本文は理由と条件だけを述べ、図は構造を担う")
                if v["id"] == "fig-pipeline": v["uploaded_asset"] = "asset-001"
            self.put_json("plan/visual-plan.yaml", data)
            return
        if kind == "draft":
            self.log.append(identifier); self.check_intent(task)
            packet = (WORK / f"plan/chapter-packets/{target}.yaml").read_text(encoding="utf-8")
            assert "publication_architecture:" in packet and "章末問題はいらない" in packet, "packet carries the architecture and the verbatim intent"
            assert any("FORBIDDEN" in line and "exercises" in line for line in task["instructions"]), "drafting is told what is forbidden"
            draft = AGENT / f"chapters/{target}.draft.md"
            self.copy(f"chapters/{target}.draft.md" if draft.exists() else f"chapters/{target}.md", self.chapter_file(target))
            self.transform(target)
            summary, concepts = SUMMARIES[target]
            self.put_json(f"plan/summaries/{target}.yaml", {"summary": summary, "introduced_concepts": concepts, "key_terms": [], "handoff": "次章へ渡す前提を明記した。",
                                                             "intent_check": "章末問題を入れず、ケースと図表を優先し、硬すぎない語り口にした。"})
            return
        if identifier == "plan-assets":
            self.log.append(identifier); self.check_intent(task)
            self.copy("plan/assets-plan.yaml", "plan/assets-plan.yaml")
            plan = job_yaml(WORK / "plan/assets-plan.yaml")
            plan["assets"].append({"id": "fig-pipeline", "device": "fig-pipeline", "type": "screenshot", "chapter": "ch-mechanism", "section": "sec-mechanism-multihead",
                                   "placement": "マルチヘッド注意の説明の後", "purpose": "ユーザー提供の処理パイプライン図で流れを一望させる", "caption": "Transformerの処理パイプライン",
                                   "path": "source/assets/uploaded/pipeline.png", "uploaded_asset": "asset-001", "provenance": "ユーザー提供画像（asset-001）",
                                   "information_shape": {"kind": "source_image"}, "improvement_claim": {"kinds": ["orient_reader"], "statement": "処理の流れを一枚で見渡せる"},
                                   "factual_basis": "source", "source_ids": [mapping["transformer-architecture"]]})
            plan["uploaded_assets"] = [{"asset": "asset-001", "decision": "placed", "asset_id": "fig-pipeline", "chapter": "ch-mechanism",
                                        "reason": "指示どおり第2章の処理の流れの説明箇所に配置し、表紙には使っていない", "credit": "提供：著者"}]
            self.put_json("plan/assets-plan.yaml", plan)
            return
        super().handle(task)
        if identifier == "synthesize":
            clusters = job_yaml(WORK / "plan/source-clusters.yaml")
            clusters["clusters"].append({"id": "cl-practice", "label": "現場の経験（背景資料）", "sources": [mapping["practitioner-notes"], mapping["field-notes"]]})
            self.put_json("plan/source-clusters.yaml", clusters)
        if kind in ("expand", "review") or (kind == "rewrite" and target == "ch-training"): self.transform(target)
        if identifier == "design":
            decisions = job_yaml(WORK / "plan/design-decisions.yaml")
            decisions["layout_references_applied"] = [{"asset": "asset-002", "adopted": "外側余白と2階層の見出し", "not_adopted": "判型（WebUIの選択を維持）",
                                                        "reason": "レイアウト参考は構成だけを参考にする指示"}]
            decisions["intent_check"] = "固すぎない語り口に合わせ、余白を広めにした。"
            self.put_json("plan/design-decisions.yaml", decisions)

    def chapter_file(self, chapter):
        return next(c["file"] for c in job_yaml(WORK / "source/metadata/outline.yaml")["chapters"] if c["id"] == chapter)

    def transform(self, chapter):
        """The manuscript follows the chapter's editorial plan (no routine summaries; a case; the uploaded figure)."""
        path = WORK / self.chapter_file(chapter)
        text = path.read_text(encoding="utf-8")
        if chapter in ("ch-foundations", "ch-evaluation"): text = unwrap(text, f"{chapter}-key-points")
        if chapter == "ch-training":
            text = text.replace("::: {.summary #ch-training-key-points}", '::: {.checklist .next-actions #ch-training-next-actions title="次にやること"}')
            if "cs-training-warmup" not in text:
                text = text.replace("## スケーリング則とその修正", "::: {.case-study #cs-training-warmup}\nある実験では、ウォームアップを省いたところ最初の数百ステップで損失が発散した。"
                                    "学習率を段階的に上げる設定に戻すと、同じ計算量で安定して収束した。\n:::\n\n## スケーリング則とその修正", 1)
        if chapter == "ch-mechanism" and "fig-pipeline" not in text:
            text = text.replace("## 計算量と効率化", "![Transformerの処理パイプライン](source/assets/uploaded/pipeline.png){#fig-pipeline}\n\n## 計算量と効率化", 1)
        path.write_text(text, encoding="utf-8")



def patch_analyze(agent):
    original = agent.handle
    def handle(task):
        if task["id"].startswith("analyze:"):
            mapping, _ = agent.ids(); by_id = {v: k for k, v in mapping.items()}
            agent.log.append(task["id"]); agent.check_intent(task)
            for output in task["outputs"]:
                sid = Path(output).stem
                if by_id[sid] == "field-notes":
                    agent.put_json(output, {"source": sid, "relevance": "supporting", "reliability": "tertiary", "summary": "注意機構モデルを社内検索に導入した現場の記録。"
                                    "長文の遅さ、評価のずれ、学習の不安定さについての体験を述べる。" * 2, "key_claims": [{"text": "現場では入力分割で文脈が途切れた", "locator": "第1段落"}],
                                    "source_role": "evidence",   # the agent's estimate; the user's URL role (background) must win
                                    "bibliographic": {"title": "現場メモ：注意機構モデルの運用で困ったこと", "authors": ["高橋 三郎"], "published": "2025", "type": "webpage"}})
                elif by_id[sid] == "practitioner-notes":
                    agent.put_json(output, {"source": sid, "relevance": "supporting", "reliability": "tertiary", "summary": "エンジニアが注意機構モデルを一年運用した体験記。"
                                    "推論時間、評価のずれ、学習の不安定さについての現場の実感を述べる。" * 2, "key_claims": [{"text": "実運用ではベンチマークと満足度がずれる", "locator": "第2段落"}],
                                    "source_role": "background", "authority": "professional_experience",
                                    "bibliographic": {"title": "現場でTransformerを運用して感じたこと", "authors": ["佐藤一郎"], "published": "2025-02-01", "type": "post-weblog"}})
                else: agent.copy(f"notes/{by_id[sid]}.yaml", output, sid)
            return
        original(task)
    agent.handle = handle


def assertions(agent):
    summary = json.loads((WORK / "execution-summary.json").read_text(encoding="utf-8"))
    assert summary["complete"], summary["publication_status"]
    project = json.loads((WORK / "project.json").read_text(encoding="utf-8"))
    # WebUI -> config
    assert project["publication_architecture"] == {"mode": "auto"}
    assert project["citations"]["in_text_citation_style"] == "note" and project["citations"]["bibliography_numbering"] == "numbered"
    assert [a["usage"]["role"] for a in project["input"]["assets"]] == ["asset", "layout_reference", "layout_reference"]
    assert project["input"]["assets"][1]["path"] == "input/assets/layout-sample.pdf"
    field_url = next(u for u in project["input"]["urls"] if u.endswith("field-notes.html"))
    assert project["input"]["url_usage"][field_url]["role"] == "background" and project["input"]["url_usage"][field_url]["role_origin"] == "user"
    assert not any(u.endswith("layout-sample-page.html") for u in project["input"]["urls"]), "a layout-reference URL is not a content URL"
    assert any(a.get("url", "").endswith("layout-sample-page.html") and a["usage"]["role"] == "layout_reference" for a in project["input"]["assets"])
    background = next(s for s in project["input"]["sources"] if s["original_name"] == "practitioner-notes.md")
    assert background["usage"]["role"] == "further_reading"
    task_md = (WORK / "TASK.md").read_text(encoding="utf-8")
    assert "## Publication architecture" in task_md and "## Inputs and their roles" in task_md and "layout_reference" in task_md
    # config -> orchestration: phases
    events = [json.loads(x) for x in (WORK / "run-events.jsonl").read_text(encoding="utf-8").splitlines()]
    done = [e["task"] for e in events if e["event"] == "agent_done"]
    order = [t for t in done if t in ("publication-plan", "architecture", "visual-plan", "draft:ch-foundations")]
    assert order == ["publication-plan", "architecture", "visual-plan", "draft:ch-foundations"], order
    assert {"publication_planning", "visual_planning", "drafting", "design", "layout"} <= agent.intent_tasks, agent.intent_tasks
    # publication plan
    arch = job_yaml(WORK / "plan/publication-architecture.yaml")
    assert "exercises" in arch["block_policy"]["forbidden"] and arch["exercise_policy"] == "none"
    assert "case_study" in arch["block_policy"]["preferred"] and arch["visual_policy"]["density"] == "high"
    roles = job_yaml(WORK / "plan/source-roles.yaml")["sources"]
    practitioner = next(k for k, v in roles.items() if "現場" in str(v.get("title")))
    assert roles[practitioner]["role"] == "further_reading" and roles[practitioner]["citation_allowed"] in (False, "false")
    index = json.loads((WORK / "research/index.json").read_text(encoding="utf-8"))
    assert not any("layout-sample" in str(s.get("path") or s.get("url")) or "pipeline" in str(s.get("path")) for s in index["sources"]), "references and assets are not sources"
    field = next(k for k, v in roles.items() if "現場メモ" in str(v.get("title")))
    assert roles[field]["role"] == "background" and roles[field]["role_origin"] == "user" and roles[field]["citation_allowed"] in (False, "false"), roles[field]
    transformer = next(k for k, v in roles.items() if "Transformerの構造" in str(v.get("title")))
    assert roles[transformer]["authority"] == "expert_commentary" and roles[transformer]["intended_usage"] == "第2章の構造の説明"
    # manuscript: no exercises, chapters differ, the uploaded figure is where the user asked
    manuscript = {p.name: p.read_text(encoding="utf-8") for p in (WORK / "source/manuscript").glob("*.md")}
    assert not any(".exercise" in t for t in manuscript.values())
    assert "source/assets/uploaded/pipeline.png" in manuscript["02-mechanism.md"]
    qa = job_yaml(WORK / "reports/publication-architecture-qa.yaml")
    assert qa["ok"] in (True, "true") and not [f for f in qa["findings"] if f["severity"] == "high" and not f.get("waived")], qa["findings"]
    assert "fix-architecture-qa" in done, "an unmet explicit wish blocked completion until it was fixed or waived with a reason"
    endings = qa["summary"]["chapter_endings"]
    assert len({tuple(v) for v in endings.values()}) > 1, endings
    assert "mechanical_chapter_end" not in {f["rule"] for f in qa["findings"]}
    visual = job_yaml(WORK / "reports/visual-plan-qa.yaml")
    assert visual["ok"] in (True, "true") and int(visual["summary"]["distinct_types"]) == 3, visual["summary"]
    # citations: footnotes in the text, numbered and grouped back matter
    bib = json.loads((WORK / "reports/bibliography.json").read_text(encoding="utf-8"))
    groups = {g["group"]: g for g in bib["groups"]}
    assert groups["cited"]["numbered"] and groups["cited"]["entries"][0]["number"] == 1
    assert practitioner in [e["id"] for e in groups["background"]["entries"]] and practitioner not in bib["cited_in_text"], "further_reading is explicitly listed, never cited"
    assert field not in [e["id"] for e in groups["background"]["entries"]] and field not in bib["cited_in_text"], "background URL is authoring-only"
    assert "asset-001" in [e["id"] for e in groups["visual"]["entries"]]
    assert "design" not in groups, "design references are off by default"
    site = (WORK / "interchange/book.html").read_text(encoding="utf-8")
    assert 'class="footnote-ref"' in site, "footnote citations"
    refs = site.split('id="refs"')[1]
    assert re.search(r"引用文献[\s\S]*\[1\]", refs) and re.search(r"参考資料[\s\S]*\[1\] 佐藤一郎", refs) and "図表・画像出典" in refs, "grouped numbered lists"
    assert "layout-sample" not in refs
    if shutil.which("pdftotext"):
        text = subprocess.run(["pdftotext", str(WORK / "publish/book.pdf"), "-"], capture_output=True, text=True).stdout
        assert "引用文献" in text and "参考資料" in text and "[1]" in text, "PDF back matter"
    gates = json.loads((WORK / "reports/completion-gates.json").read_text(encoding="utf-8"))
    assert gates["passed"] and next(g for g in gates["gates"] if g["id"] == 23)["passed"]
    decisions = job_yaml(WORK / "plan/design-decisions.yaml")
    assert decisions["layout_references_applied"][0]["asset"] == "asset-002"
    assert summary["publication_architecture"]["mode"] == "auto" and "exercises" in summary["publication_architecture"]["forbidden_blocks"]
    return summary, qa, bib


def main():
    server, base = serve()
    try:
        generate(base)
        mini_e2e.WORK = WORK
        sys.path.insert(0, str(WORK / "scripts"))
        agent = ArchitectureAgent(base); patch_analyze(agent)
        result, steps = run_goal(agent, limit=160)
        summary, qa, bib = assertions(agent)
        print(f"PASS architecture E2E in {steps} goal iterations; tasks handled: {len(agent.log)}")
        print(json.dumps({"architecture": summary["publication_architecture"], "qa": qa["summary"],
                          "bibliography": [(g["title"], [e["number"] for e in g["entries"]]) for g in bib["groups"]]}, ensure_ascii=False, indent=1))
        print("Workspace:", WORK)
    finally:
        server.shutdown()
        if "--keep" not in sys.argv and WORK.parent.exists() and os.environ.get("KEEP") != "1": pass


if __name__ == "__main__":
    main()
