"""Development/regression aid: approximate layout metrics of ANY PDF with pdfplumber.

The job runtime measures layout with `typst eval` (job-template/scripts/layout_metrics.py) and needs no Python
packages. This tool is for maintainers: it measures PDFs whose Typst source is not available (for example books
generated by earlier versions) and cross-checks the runtime metrics on the same PDF. It uses heuristics
(graphics, rules, filled boxes, captions, large chapter numerals), so treat small differences as noise.

Usage: python tools/pdf-layout-audit.py book.pdf [--json out.json] [--back-from PAGE]
Requires: pip install pdfplumber
"""
import argparse
from collections import Counter
import json
import re
import sys

CAPTION = re.compile(r"^(図|表|Fig\.?|Figure|Table)\s?\d")
BACK = re.compile(r"^(参考文献|文献|References|Bibliography|索引|Index)\s*$")


def page_facts(page, body_size):
    height, width = page.height, page.width
    body = [c for c in page.chars if c["text"].strip() and 0.08 * height < c["top"] < 0.92 * height]
    lines = page.extract_text_lines() if hasattr(page, "extract_text_lines") else []
    starts = [l["text"].strip() for l in lines]
    filled = [r for r in page.rects if r.get("fill") and r["width"] * r["height"] > 1500 and r["width"] < 0.98 * width]
    rules = [l for l in page.lines if abs(l["y0"] - l["y1"]) < 1 and l["x1"] - l["x0"] > 0.3 * width]
    big = [c for c in page.chars if c["text"].strip() and c["size"] >= 2.0 * body_size]
    captions = [s for s in starts if CAPTION.match(s)]
    graphics = len(page.images) + (1 if len(page.curves) >= 3 else 0)
    return {"chars": len(body), "images": len(page.images), "curves": len(page.curves), "filled_boxes": len(filled),
            "rules": len(rules), "captions": captions, "chapter_numeral": bool(big),
            "first_line": starts[0] if starts else "", "graphics": graphics,
            "lines": starts[:4], "back_heading": any(BACK.match(s) for s in starts)}


def audit(path, back_from=None):
    import pdfplumber
    with pdfplumber.open(path) as pdf:
        sizes = Counter(round(c["size"], 1) for p in pdf.pages for c in p.chars if c["text"].strip())
        body_size = sizes.most_common(1)[0][0] if sizes else 10.0
        facts = [page_facts(p, body_size) for p in pdf.pages]
    toc = re.compile(r"^(目次|Contents)\s*$")
    openers = [i + 1 for i, f in enumerate(facts) if f["chapter_numeral"] and i > 0 and not any(toc.match(l) for l in f["lines"])]
    first = openers[0] if openers else 1
    back = back_from or next((i + 1 for i, f in enumerate(facts) if i + 1 > (openers[-1] if openers else 0)
                              and f["back_heading"]), len(facts) + 1)
    pages = []
    for number, f in enumerate(facts, 1):
        region = "front" if number < first else "back" if number >= back else "main"
        pause = bool(number in openers or f["graphics"] or f["filled_boxes"] or f["captions"] or f["rules"] >= 3)
        pages.append({"page": number, "region": region, "chars": f["chars"], "pause": pause,
                      "text_only": region == "main" and not pause and f["chars"] > 0,
                      "captions": f["captions"], "filled_boxes": f["filled_boxes"], "graphics": f["graphics"]})
    runs, current = [], []
    for p in pages:
        if p["text_only"] and (not current or p["page"] == current[-1] + 1): current.append(p["page"])
        else:
            if current: runs.append(current)
            current = [p["page"]] if p["text_only"] else []
    if current: runs.append(current)
    runs = sorted(({"start": r[0], "end": r[-1], "length": len(r)} for r in runs), key=lambda r: (-r["length"], r["start"]))
    main = [p for p in pages if p["region"] == "main"]
    bounds = openers + [back]
    chapters = []
    for index, start in enumerate(openers):
        end = bounds[index + 1] - 1
        span = [p for p in pages if start <= p["page"] <= end]
        chapters.append({"pages": [start, end], "page_count": len(span), "chars": sum(p["chars"] for p in span),
                         "captions": sum(len(p["captions"]) for p in span), "boxes": sum(p["filled_boxes"] for p in span),
                         "text_only_pages": sum(p["text_only"] for p in span),
                         "max_text_only_run": max((r["length"] for r in runs if start <= r["start"] <= end), default=0)})
    captions = sum(len(p["captions"]) for p in main)
    chars = sum(p["chars"] for p in main)
    return {"method": "pdfplumber-heuristic", "body_font_pt": body_size,
            "totals": {"pages": len(pages), "front_matter_pages": first - 1, "main_pages": len(main),
                       "back_matter_pages": sum(p["region"] == "back" for p in pages), "chapters": len(chapters),
                       "chars_per_main_page": round(chars / len(main)) if main else 0,
                       "captions": captions, "captions_per_10k_chars": round(captions * 10000 / chars, 2) if chars else None,
                       "filled_boxes": sum(p["filled_boxes"] for p in main),
                       "text_only_pages": sum(p["text_only"] for p in main),
                       "max_text_only_run": runs[0]["length"] if runs else 0,
                       "text_only_runs_at_least": {str(n): sum(r["length"] >= n for r in runs) for n in (3, 4, 5, 8)}},
            "max_text_only_run": runs[0] if runs else None, "text_only_runs": runs, "chapters": chapters, "pages": pages}


def as_layout_metrics(result):
    """Shape the heuristic audit like reports/layout-metrics.json so scripts/pacing.py can judge old PDFs."""
    chapters = [{"id": f"ch{i + 1}", "label": f"ch{i + 1}", "pages": c["pages"], "page_count": c["page_count"],
                 "elements": {"table": 0, "summary": 0, "case-study": 0, "callout": c["boxes"], "pull-quote": 0},
                 "visuals": c["captions"], "visuals_per_10k_chars": round(c["captions"] * 10000 / c["chars"], 2) if c["chars"] else None,
                 "nonprose_share": None, "text_only_pages": c["text_only_pages"], "max_text_only_run": c["max_text_only_run"]}
                for i, c in enumerate(result["chapters"])]
    chapter_of = lambda page: next((c["id"] for c in chapters if c["pages"][0] <= page <= c["pages"][1]), None)
    pages = [{"page": p["page"], "region": p["region"], "chapter": chapter_of(p["page"]), "prose_chars": p["chars"],
              "text_only": p["text_only"], "headings": []} for p in result["pages"]]
    spreads = [{"pages": [n, n + 1], "chapter": chapter_of(n + 1), "region": "main" if all(pages[q - 1]["region"] == "main" for q in (n, n + 1)) else "mixed",
                "text_only": pages[n - 1]["text_only"] and pages[n]["text_only"]} for n in range(2, len(pages), 2)]
    totals = dict(result["totals"], nonprose_share=None, text_only_spreads=sum(s["text_only"] and s["region"] == "main" for s in spreads))
    runs = [dict(r, chapter=chapter_of(r["start"])) for r in result["text_only_runs"]]
    return {"generated_at": "pdf-layout-audit", "definitions": {"method": "pdfplumber heuristic"}, "totals": totals,
            "text_only_runs": runs, "chapters": chapters, "pages": pages, "spreads": spreads}


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("pdf"); parser.add_argument("--json"); parser.add_argument("--back-from", type=int)
    parser.add_argument("--pacing", choices=("short", "standard", "long", "monograph"), help="judge with the pacing gate at this tier")
    args = parser.parse_args()
    result = audit(args.pdf, args.back_from)
    if args.pacing:
        from pathlib import Path
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "job-template/scripts"))
        import pacing
        try:  # the tier's own profile file is the authority; the constant is the fallback
            import publication_profile
            max_pages = int(publication_profile.load_data("tiers", args.pacing)["rhythm"]["max_text_only_pages"]); source = f"profiles/tiers/{args.pacing}.yaml"
        except Exception: max_pages, source = pacing.TIER_LIMITS[args.pacing], "pacing.TIER_LIMITS"
        limit = {"tier": args.pacing, "max_text_only_pages": max_pages, "source": source}
        result["pacing"] = pacing.evaluate(as_layout_metrics(result), limit)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as out: json.dump(result, out, ensure_ascii=False, indent=2)
    t = result["totals"]; r = result["max_text_only_run"]
    print(json.dumps(t, ensure_ascii=False))
    if r: print(f"longest text-only run: pp. {r['start']}-{r['end']} ({r['length']} pages)")
    for c in result["chapters"]: print(json.dumps(c, ensure_ascii=False))
    if args.pacing:
        verdict = result["pacing"]
        print(f"pacing ({args.pacing}, limit {verdict['limits']['max_text_only_pages']}): {verdict['verdict'].upper()} — "
              f"{verdict['summary']['high']} high, {verdict['summary']['medium']} medium; chapters over the limit: "
              + (", ".join(verdict["summary"]["chapters_over_limit"]) or "none"))
        for finding in verdict["findings"]: print(f"  [{finding['severity']}] {finding['rule']}: {finding.get('chapter')} {finding['detail']}")


if __name__ == "__main__":
    sys.exit(main())
